INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Corrientes' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Capital Federal' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Buenos Aires' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Catamarca' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Cordoba' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Chaco' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Chubut' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Entre Rios' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Formosa' );

INSERT INTO PERSON (ID, CREATED_DATE, LAST_MODIFIED_DATE, ENABLED, FIRST_NAME, LAST_NAME, COUNTRY_ISO_CODE, CITY_NAME)
VALUES (PERSON_SEQUENCE.nextval, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, true, CONCAT('test', cast(PERSON_SEQUENCE.currval as VARCHAR(5))), 'test', 'AR', 'Jujuy' );