CREATE TABLE job (
    name VARCHAR(255),
    created_date TIMESTAMP NOT NULL,
    last_modified_date TIMESTAMP NOT NULL,
    CONSTRAINT PK_JOB PRIMARY KEY (name)
);

CREATE TABLE person_job (
    person_id BIGINT NOT NULL,
    job_name VARCHAR(255) NOT NULL,
    CONSTRAINT PK_PERSON_JOB PRIMARY KEY (person_id, job_name),
    CONSTRAINT FK_PERSON_JOB_PERSON FOREIGN KEY (person_id) REFERENCES PERSON,
    CONSTRAINT FK_PERSON_JOB_JOB FOREIGN KEY (job_name) REFERENCES JOB
);