name: Continuous Integration

on:
  push:
    branches:
      - main
  release:
    types: [ published ]

jobs:
  build:
    name: Run Unit & Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Execute all Unit & Integration Tests
        run: make run-tests-with-report

      - name: Publish Test Report
        if: ${{ always() }}
        uses: scacap/action-surefire-report@v1

      - name: Build Artifact
        id: buildArtifact
        run: |
          make build
          echo "::set-output name=file::$(ls target/*exec.jar)"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: ${{ steps.buildArtifact.outputs.file }}